version: '3.7'
services:
  db:
    image: library/postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=sabbotage
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

    ports:
      - '5432:5432'

    volumes:
      - ./data:/var/lib/postgresql/data
